# Generated by Django 3.1.7 on 2021-03-29 15:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('sub_title', models.CharField(blank=True, help_text='Пример: Образование, Курсы, Технологии и т.д.', max_length=100, null=True, verbose_name='Под заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Фото')),
                ('descrip', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
