# Generated by Django 3.1.7 on 2021-03-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_and', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
