# Generated by Django 3.1.7 on 2021-03-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_aboutus_one_small_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='four_big_image',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='three_big_image',
        ),
    ]
