# Generated by Django 3.1.7 on 2021-03-16 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Иконка категории')),
                ('image', models.ImageField(upload_to='courses/', verbose_name='Фото категории')),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Под заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cources.categorycourses', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
