# Generated by Django 3.1.7 on 2021-03-29 15:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Под заголовок')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Иконка категории')),
                ('image', models.ImageField(upload_to='courses/', verbose_name='Фото категории')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
