# Generated by Django 3.1.7 on 2021-03-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0004_auto_20210317_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycourses',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Под заголовок'),
        ),
    ]
