# Generated by Django 3.1.7 on 2021-03-29 15:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Название сайта')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Логотип сайта')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Слоган')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание сайта')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('phone_1', models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер 1го телефона')),
                ('phone_2', models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер 2го телефона')),
                ('email', models.CharField(blank=True, max_length=155, null=True, verbose_name='E-mail')),
                ('time_work', models.CharField(blank=True, max_length=255, null=True, verbose_name='Время работы')),
                ('banner_big_photo', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Главный баннер на сайте')),
                ('banner_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Баннер большой заголовок')),
                ('banner_big_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Баннер мини заголовок')),
                ('banner_desc', models.TextField(blank=True, null=True, verbose_name='Баннер большой Описание')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Instagram')),
                ('whatsapp', models.CharField(blank=True, max_length=13, null=True, verbose_name='WhatsApp номер')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Facebook')),
                ('usloviya', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Условия приема')),
                ('politic_polojeniya', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Политика и Положения')),
            ],
            options={
                'verbose_name_plural': 'Основные настройки',
            },
        ),
    ]
