# Generated by Django 3.1.7 on 2021-03-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='banner_big_photo',
            field=models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Главный баннер на сайте'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='banner_big_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Баннер мини заголовок'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='banner_button',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Баннер кнопка название'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='banner_desc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Баннер большой Описание'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='banner_small_photo',
            field=models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Маленький баннер на сайте'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='banner_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Баннер большой заголовок'),
        ),
    ]
