# Generated by Django 3.1.7 on 2021-03-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='usloviya',
            field=models.TextField(blank=True, null=True, verbose_name='Условия приема'),
        ),
    ]
