# Generated by Django 3.1.7 on 2021-03-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210313_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='banner_desc',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Баннер большой Описание'),
        ),
    ]
