# Generated by Django 3.1.7 on 2021-03-17 08:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_setting_usloviya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='usloviya',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Условия приема'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='vacancie',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Вакансии'),
        ),
    ]
