# Generated by Django 3.1.7 on 2021-03-18 07:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210317_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='banner_button',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='banner_small_photo',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='vacancie',
        ),
        migrations.AddField(
            model_name='setting',
            name='politic_polojeniya',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Политика и Положения'),
        ),
    ]
