# Generated by Django 3.1.7 on 2021-04-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210318_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='banner_big_photo',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='setting',
            name='banner_big_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Баннер мини заголовок'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='banner_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Баннер большой заголовок'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='Название сайта'),
        ),
    ]
