# Generated by Django 3.1.7 on 2021-03-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя Фамилие')),
                ('sub_title', models.CharField(blank=True, help_text='Пример: Учитель по программированию, Робототехнике, Английскому и т.д.', max_length=50, null=True, verbose_name='Предмет')),
                ('image', models.ImageField(blank=True, null=True, upload_to='teacher/', verbose_name='Фото')),
                ('descrip', models.TextField(blank=True, null=True, verbose_name='Описание того кто он(а) и что закончил(а)')),
            ],
            options={
                'verbose_name_plural': 'Преподы',
            },
        ),
    ]
