# Generated by Django 3.1.7 on 2021-03-29 15:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='descrip',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание того кто он(а) и что закончил(а)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sub_title',
            field=models.CharField(blank=True, help_text='Пример: Учитель по программированию, Робототехнике, Английскому и т.д.', max_length=100, null=True, verbose_name='Предмет'),
        ),
    ]
