# Generated by Django 3.1.7 on 2021-03-29 15:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Имя Фамилие')),
                ('sub_title', models.CharField(blank=True, help_text='Пример: Окончил курс по Программированию, Робототехнике и т.д.', max_length=100, null=True, verbose_name='Курс')),
                ('testimonial', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Отзыв человека')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
