# Generated by Django 3.1.7 on 2021-03-17 08:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_remove_testimonial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Отзыв человека'),
        ),
    ]
