# Generated by Django 3.1.7 on 2021-03-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0003_auto_20210317_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='sub_title',
            field=models.CharField(blank=True, help_text='Пример: Окончил курс по Программированию, Робототехнике и т.д.', max_length=100, null=True, verbose_name='Курс'),
        ),
    ]
