# Generated by Django 3.1.7 on 2021-04-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0004_auto_20210317_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='sub_title',
            field=models.CharField(blank=True, help_text='Пример: Окончил курс по Программированию, Робототехнике и т.д.', max_length=200, null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Имя Фамилие'),
        ),
    ]
